SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[COUNTRIES] (
		[COUNTRY_ID]       [char](2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[COUNTRY_NAME]     [varchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[REGION_ID]        [decimal](38, 0) NULL
)
GO
ALTER TABLE [dbo].[COUNTRIES] SET (LOCK_ESCALATION = TABLE)
GO
