SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[DEPARTMENTS] (
		[DEPARTMENT_ID]       [decimal](4, 0) NOT NULL,
		[DEPARTMENT_NAME]     [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[MANAGER_ID]          [decimal](6, 0) NULL,
		[LOCATION_ID]         [decimal](4, 0) NULL
)
GO
ALTER TABLE [dbo].[DEPARTMENTS] SET (LOCK_ESCALATION = TABLE)
GO
