CREATE USER [BMF_SS_MOVIES]
	WITHOUT LOGIN
	WITH DEFAULT_SCHEMA = [dbo]
GO
GRANT ALTER
	ON USER::[BMF_SS_MOVIES]
	TO [guest]
GO
GRANT CONTROL
	ON USER::[BMF_SS_MOVIES]
	TO [guest]
GO
GRANT IMPERSONATE
	ON USER::[BMF_SS_MOVIES]
	TO [guest]
GO
GRANT VIEW DEFINITION
	ON USER::[BMF_SS_MOVIES]
	TO [guest]
GO
